import { useEffect, useState } from 'react'
import { useAuth } from '../AuthContext'
import client from '../api/client'

export default function Admin(){const{isLogin,role}=useAuth();const[f,sf]=useState({couponName:'',totalStock:100,perUserMax:1,endHours:24});const[shop,setShop]=useState(null);const[editing,setEditing]=useState(false);const[m,sm]=useState('');
useEffect(()=>{if(isLogin&&role==='MERCHANT')client.get('/merchant/me').then(({data})=>setShop(data)).catch(e=>sm('店铺加载失败：'+(e.response?.data?.message||e.message)))},[isLogin,role]);
if(!isLogin||role!=='MERCHANT')return <div className="empty">请先登录商家账号</div>;
const create=async e=>{e.preventDefault();sm('');try{const n=new Date(),d=new Date(n.getTime()+f.endHours*36e5);const{data}=await client.post('/coupon/create',{couponName:f.couponName,totalStock:+f.totalStock,remainStock:+f.totalStock,startTime:n.toISOString(),endTime:d.toISOString(),perUserMax:+f.perUserMax,status:1});setShop(s=>({...s,coupons:[data,...(s?.coupons||[])],couponCount:(s?.couponCount||0)+1}));sm('已创建 '+data.couponName+' · 库存 '+data.totalStock)}catch(e){sm('创建失败：'+(e.response?.data?.message||e.message))}};
const saveShop=async e=>{e.preventDefault();try{const{data}=await client.put('/merchant/'+shop.id,shop);setShop(s=>({...s,...data}));setEditing(false);sm('店铺信息已保存')}catch(e){sm('保存失败：'+(e.response?.data?.message||e.message))}};
const drill=async s=>{try{await client.post('/drill/start?scenario='+s);await new Promise(r=>setTimeout(r,3000));const{data}=await client.post('/drill/recover');sm(s+' 演练完成 · '+data.durationMs+'ms')}catch{sm('演练失败')}};
return <><div className="section-head"><div><h2>{shop?.shopName||'商家工作台'}</h2><div className="muted">这里只显示当前登录商户的店铺和优惠券</div></div></div>{shop&&<div className="panel" style={{marginBottom:16}}><div className="section-head"><div><h3>店铺资料</h3><div className="muted">店铺 ID：{shop.id}</div></div><button className="logout" onClick={()=>setEditing(!editing)}>{editing?'取消':'编辑资料'}</button></div>{editing?<form onSubmit={saveShop}><div className="form-grid"><div className="field"><label>店铺名称</label><input className="input" value={shop.shopName||''} onChange={e=>setShop({...shop,shopName:e.target.value})}/></div><div className="field"><label>分类</label><input className="input" value={shop.category||''} onChange={e=>setShop({...shop,category:e.target.value})}/></div></div><div className="field"><label>店铺介绍</label><textarea className="input" value={shop.shopDesc||''} onChange={e=>setShop({...shop,shopDesc:e.target.value})}/></div><button className="primary-btn" type="submit">保存店铺资料</button></form>:<p className="muted">{shop.category||'其他'} · {shop.shopDesc||'还没有店铺介绍'}</p>}</div>}<div className="form-grid"><div className="panel"><h3>创建一张优惠券</h3><form onSubmit={create}><div className="field"><label>优惠券名称</label><input className="input" required value={f.couponName} onChange={e=>sf({...f,couponName:e.target.value})} placeholder="例如：新客专享立减券" /></div><div className="form-grid" style={{gridTemplateColumns:'1fr 1fr 1fr',gap:10}}><div className="field"><label>总库存</label><input className="input" type="number" min="1" value={f.totalStock} onChange={e=>sf({...f,totalStock:e.target.value})}/></div><div className="field"><label>每人限购</label><input className="input" type="number" min="1" value={f.perUserMax} onChange={e=>sf({...f,perUserMax:e.target.value})}/></div><div className="field"><label>有效时长（小时）</label><input className="input" type="number" min="1" value={f.endHours} onChange={e=>sf({...f,endHours:e.target.value})}/></div></div><button className="primary-btn" type="submit">创建活动并预热 Redis</button></form>{m&&<p className="muted" style={{color:m.startsWith('失败')||m.startsWith('创建失败')?'#ff2442':'#10a37f'}}>{m}</p>}</div><div className="panel"><h3>我的优惠券</h3><div className="muted" style={{marginBottom:12}}>共 {shop?.couponCount||0} 张，仅展示本店活动</div>{(shop?.coupons||[]).length===0?<div className="empty">还没有优惠券</div>:<div style={{display:'grid',gap:10}}>{shop.coupons.map(c=><div key={c.id} style={{padding:'12px 0',borderBottom:'1px solid #f3f3f3'}}><strong>{c.couponName}</strong><div className="muted">库存 {c.remainStock} / {c.totalStock} · 每人 {c.perUserMax} 张</div></div>)}</div>}</div></div><div className="panel" style={{marginTop:16}}><h3>故障演练</h3><p className="muted">在真实流量前验证降级和恢复能力。</p><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10}}>{[['redis','Redis'],['mq','RabbitMQ'],['db','数据库'],['network','网络']].map(([s,n])=><button className="logout" style={{padding:16}} key={s} onClick={()=>drill(s)}>演练 {n}</button>)}</div></div></>}
