import { useState } from 'react'
import client from '../api/client'

const EXAMPLES=['分析最近7天经营情况','检查当前活动的风控风险','帮我策划双11秒杀活动','新用户优惠券应该怎么配置？']
const AGENTS=[['data','数据分析 Agent'],['risk','风控诊断 Agent'],['content','内容生成 Agent'],['strategy','策略推荐 Agent']]

export default function AIPage(){
  const[q,sq]=useState('');const[result,setResult]=useState(null);const[loading,setLoading]=useState(false);const[executing,setExecuting]=useState(false);const[msg,setMsg]=useState('')
  const ask=async()=>{if(!q.trim())return;setLoading(true);setMsg('');try{const{data}=await client.post('/ai/copilot/query',{query:q});setResult(data)}catch(e){setMsg(e.response?.data?.message||'Copilot 暂时不可用')}finally{setLoading(false)}}
  const execute=async()=>{setExecuting(true);setMsg('');try{const{data}=await client.post('/ai/copilot/execute',{query:q});setMsg('已创建优惠券：'+data.couponName+' · 库存 '+data.stock+' · 有效 '+data.durationHours+' 小时')}catch(e){setMsg(e.response?.data?.message||'执行失败')}finally{setExecuting(false)}}
  const metrics=result?.metrics||{};const risks=result?.risks||{};const agents=result?.agents||{}
  return <><div className="section-head"><div><h2>AI 运营 Copilot</h2><div className="muted">先读真实数据，再分析风险，最后执行动作</div></div><span className="muted">4 Agents · Tool-grounded</span></div><div className="panel"><div style={{display:'flex',gap:10}}><input className="input" value={q} onChange={e=>sq(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="问问你的运营搭档：分析订单、检查风险或策划活动" /><button className="primary-btn" onClick={ask} disabled={loading}>{loading?'分析中…':'开始分析'}</button></div><div className="filters" style={{marginTop:14}}>{EXAMPLES.map(x=><button className="filter" key={x} onClick={()=>sq(x)}>{x}</button>)}</div></div>{msg&&<div className="panel" style={{marginTop:18,color:msg.startsWith('已创建')?'#10a37f':'#ff2442'}}>{msg}</div>}{result&&<div className="copilot-layout"><div className="panel"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><div><h3 style={{marginBottom:4}}>运营判断</h3><span className="muted">意图：{result.intent} · 数据快照 + Agent 并行分析 · {result.elapsedMs}ms</span></div><span className={risks.riskLevel==='LOW'?'risk-low':'risk-medium'}>风险 {risks.riskLevel||'UNKNOWN'}</span></div><div className="metric-grid"><Metric label="近7天订单" value={metrics.orders7d??'-'}/><Metric label="支付转化率" value={(metrics.paymentRate??'-')+'%'}/><Metric label="注册用户" value={metrics.registeredUsers??'-'}/><Metric label="总库存" value={metrics.totalStock??'-'}/><Metric label="剩余库存" value={metrics.remainingStock??'-'}/><Metric label="售罄率" value={(metrics.sellThroughRate??'-')+'%'}/></div><div style={{marginTop:20}}>{AGENTS.map(([key,label])=><div className="agent-block" key={key}><strong>{label}</strong><p>{agents[key]||'暂无结果'}</p></div>)}</div></div><div className="panel"><h3>可执行动作</h3><p className="muted">所有写操作都需要商家确认后执行。</p>{(result.actions||[]).map(action=><div className="action-row" key={action.id}><div><strong>{action.label}</strong><div className="muted">推荐库存 {result.recommendation?.stock||'-'} · {result.recommendation?.durationHours||'-'} 小时 · 每人 {result.recommendation?.perUserMax||'-'} 张</div></div>{action.id==='CREATE_COUPON'&&<button className="primary-btn" onClick={execute} disabled={executing}>{executing?'创建中…':'确认创建'}</button>}</div>)}<div style={{marginTop:18}}><strong>风控控制</strong><p className="muted">{(risks.controls||[]).join(' · ')}</p><p className="muted">黑名单设备：{risks.blacklistedDevices??0}</p></div></div></div>}</>
}

function Metric({label,value}){return <div className="metric-card"><span>{label}</span><strong>{value}</strong></div>}
