import { useState, useEffect } from 'react'
import { useAuth } from '../AuthContext'
import client from '../api/client'

const STATUS={CREATED:'待支付',PAYING:'支付中',PAID:'已支付',USED:'已使用',CANCELED:'已取消',EXPIRED:'已过期'}

export default function Orders(){
  const{isLogin}=useAuth(); const[orders,setOrders]=useState([]); const[loading,setLoading]=useState(true); const[selected,setSelected]=useState(null); const[paying,setPaying]=useState(false); const[msg,setMsg]=useState('')
  useEffect(()=>{if(!isLogin)return;let cancelled=false;const load=async(attempt=0)=>{try{const{data}=await client.get('/order/user');if(cancelled)return;setOrders(Array.isArray(data)?data:[]);setLoading(false);if(!data?.length&&attempt<4)setTimeout(()=>load(attempt+1),500)}catch{if(!cancelled&&attempt<4)setTimeout(()=>load(attempt+1),500);else if(!cancelled)setLoading(false)}};load();return()=>{cancelled=true}},[isLogin])
  const refresh=()=>{setLoading(true);client.get('/order/user').then(({data})=>setOrders(Array.isArray(data)?data:[])).finally(()=>setLoading(false))}
  const pay=async()=>{if(!selected)return;setPaying(true);setMsg('');try{await client.post('/order/'+selected.orderNo+'/pay');await new Promise(r=>setTimeout(r,500));await client.post('/order/'+selected.orderNo+'/pay/confirm');setOrders(orders.map(x=>x.orderNo===selected.orderNo?{...x,status:'PAID'}:x));setSelected(null);setMsg('支付成功，商品订单已更新')}catch(e){setMsg(e.response?.data?.message||'支付失败，请稍后重试')}finally{setPaying(false)}}
  const cancel=async orderNo=>{try{await client.post('/order/'+orderNo+'/cancel');setOrders(orders.map(x=>x.orderNo===orderNo?{...x,status:'CANCELED'}:x))}catch(e){setMsg(e.response?.data?.message||'取消失败，请稍后重试')}}
  const productOrders=orders.filter(o=>o.orderType==='PRODUCT_PURCHASE')
  const couponOrders=orders.filter(o=>o.orderType!=='PRODUCT_PURCHASE')

  const productList=productOrders.length?<div className="panel order-panel order-panel-products"><div className="order-header"><span>商品</span><span>订单编号</span><span>实付金额</span><span>状态 / 操作</span></div>{productOrders.map(o=><div className="order-row" key={o.orderNo}><div><strong>{o.productName||'商品订单'}</strong><div className="muted">原价 ¥{Number(o.originalAmount||o.amount||0).toFixed(2)} · 已抵扣 ¥{Number(o.discountAmount||0).toFixed(2)}</div></div><span className="muted">{o.orderNo?.slice(0,14)}...</span><strong className="order-price">¥{Number(o.amount||0).toFixed(2)}</strong><div className="order-status-action"><span className={'status-badge status-'+o.status.toLowerCase()}>{STATUS[o.status]||o.status}</span>{o.status==='CREATED'?<div className="order-actions"><button className="primary-btn" onClick={()=>{setSelected(o);setMsg('')}}>去支付</button><button className="logout" onClick={()=>cancel(o.orderNo)}>取消</button></div>:<span className="muted">已完成</span>}</div></div>)}</div>:<div className="section-empty">还没有商品订单，去店铺挑选商品吧</div>

  const couponList=couponOrders.length?<div className="panel order-panel order-panel-coupons"><div className="order-header"><span>优惠券</span><span>订单编号</span><span>领取状态</span><span>费用</span></div>{couponOrders.map(o=><div className="order-row" key={o.orderNo}><div><strong>{o.couponName||'代金券'}</strong><div className="muted">{o.shopName||'-'} · 可用于抵扣商品金额</div></div><span className="muted">{o.orderNo?.slice(0,14)}...</span><span className="status-badge status-claimed">已领取</span><span className="muted">免费领取</span></div>)}</div>:<div className="section-empty">还没有优惠券，去发现页领取优惠吧</div>

  return <><div className="section-head"><div><div className="eyebrow page-eyebrow">ACCOUNT CENTER</div><h2>我的订单</h2><div className="muted">商品订单负责支付，优惠券领取后可在结算时抵扣</div></div><button className="logout" onClick={refresh}>刷新订单</button></div>{msg&&<div className="order-message">{msg}</div>}{loading?<div className="empty">正在同步订单状态…</div>:<div className="order-sections"><section className="order-section"><div className="order-section-heading"><div><h3>商品订单</h3><span>购买商品后在这里完成支付</span></div><b>{productOrders.length}</b></div>{productList}</section><section className="order-section"><div className="order-section-heading"><div><h3>我的优惠券</h3><span>免费领取，不产生支付订单</span></div><b>{couponOrders.length}</b></div>{couponList}</section></div>}{selected&&<div className="modal-mask" onClick={()=>!paying&&setSelected(null)}><div className="payment-modal" onClick={e=>e.stopPropagation()}><div className="payment-brand">火</div><h3>确认支付商品</h3><p className="muted">{selected.productName||'商品订单'} · 订单 {selected.orderNo?.slice(0,14)}...</p><div className="payment-amount">¥{Number(selected.amount||0).toFixed(2)}</div><div className="payment-method"><div className="payment-method-active"><span>微信支付</span><b>已选择</b></div><div><span>商品订单</span><span className="muted">原价 ¥{Number(selected.originalAmount||selected.amount||0).toFixed(2)} · 优惠 ¥{Number(selected.discountAmount||0).toFixed(2)}</span></div></div><button className="primary-btn payment-submit" onClick={pay} disabled={paying}>{paying?'支付处理中…':'确认支付'}</button><button className="logout payment-cancel" onClick={()=>setSelected(null)} disabled={paying}>暂不支付</button><div className="payment-tip">本项目为支付流程演示，不会产生真实扣款</div></div></div>}</>
}
